steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "${_GCR_HOSTNAME}/$PROJECT_ID/$COMMIT_SHA:$TAG_NAME",
         "--build-arg",
         "FIREBASE_CONFIG=${_FIREBASE_CONFIG}", 
         "SLACK_BOT_TOKEN=${_SLACK_BOT_TOKEN}", 
         "SLACK_SIGNING_SECRET=${_SLACK_SIGNING_SECRET}",
         "."]

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "${_GCR_HOSTNAME}/$PROJECT_ID/$COMMIT_SHA:$TAG_NAME"]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ["run", "deploy", "${_SERVICE_NAME}", "--image", "${_GCR_HOSTNAME}/$PROJECT_ID/$COMMIT_SHA:$TAG_NAME", "--region", "${_DEPLOY_REGION}"]