version: "3.4"

services:
  deno:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: deno
    environment: 
      FIREBASE_CONFIG: ${FIREBASE_CONFIG}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
    volumes:
      - ./src:/app/src
    command: deno run --no-check=remote --allow-read --allow-env --allow-net src/app.ts
    ports:
      - '4769:4040'
